// Builds the server admin SPA's static assets ahead of time so the browser
// never compiles templates or JITs styles at runtime:
//
//   1. Compiles the in-DOM Vue template (`#app` in index.html) into a render
//      function written to assets/web/js/render.js. The dashboard then loads
//      Vue's runtime-only build (no compiler → no `unsafe-eval` in the CSP).
//   2. Regenerates the Tailwind stylesheet statically from the HTML/JS content
//      (replacing the Play-CDN JIT compiler) using the same brand-teal
//      emerald remap the CDN script used to apply.
//
// Requires Node + the pinned toolchain in target/ui-build (installed here on
// first run): `npm install @vue/compiler-dom@3.5.41 tailwindcss@3.4.17`.
//
// Run from the workspace root: `node target/ui-build/build-web-ui.js`
//
// The index.html / app.js edits this script performs are the *only* way the
// generated files should be produced; commit the generated artifacts so the
// server embeds pre-compiled assets with no build step at runtime.

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Locate the workspace root (works from scripts/ and target/ui-build/).
function workspaceRoot() {
  let dir = __dirname;
  while (!fs.existsSync(path.join(dir, 'Cargo.toml')) && path.dirname(dir) !== dir) {
    dir = path.dirname(dir);
  }
  return dir;
}

const ROOT = workspaceRoot();
const WEB = path.join(ROOT, 'crates', 'zircon-server', 'assets', 'web');
// Scratch area for the tailwind toolchain + intermediate files (gitignored).
const BUILD = path.join(ROOT, 'target', 'ui-build');
fs.mkdirSync(BUILD, { recursive: true });
const CRLF = '\r\n';

// The pinned toolchain lives in target/ui-build/node_modules; resolve from
// there whether the script runs from scripts/ or target/ui-build/.
function requireFromBuild(id) {
  return require(require.resolve(id, { paths: [path.join(BUILD, 'node_modules')] }));
}

// ---------------------------------------------------------------------------
// 1. Compile the in-DOM template into a render function
// ---------------------------------------------------------------------------
const html = fs.readFileSync(path.join(WEB, 'index.html'), 'utf8');
const open = html.indexOf('<div id="app"');
const openEnd = html.indexOf('>', open) + 1;
const closeMarker = '</div>' + CRLF + CRLF + '<script src="js/core.js">';
const close = html.lastIndexOf(closeMarker);
const alreadyConverted = open < 0 || openEnd < 0 || close < 0 || openEnd === close;

let template = '';
const templateBackupPath = path.join(BUILD, 'template.html');

if (!alreadyConverted) {
  template = html.slice(openEnd, close);
  fs.writeFileSync(templateBackupPath, template);
} else if (fs.existsSync(templateBackupPath)) {
  template = fs.readFileSync(templateBackupPath, 'utf8');
}

if (template) {
  const { compile } = requireFromBuild('@vue/compiler-dom');
  const result = compile(template, { mode: 'function', hoistStatic: true });

  const renderJs =
    '// Generated by target/ui-build/build-web-ui.js — do not edit by hand.\n' +
    '// The in-DOM #app template from index.html is compiled ahead of time so the\n' +
    '// dashboard only needs Vue\u2019s runtime build: no template compilation (and\n' +
    '// therefore no `unsafe-eval`) at runtime. See the CSP in src/web/app.rs.\n' +
    'window.ZirconRender = (function () {\n' +
    'const _Vue = window.Vue || Vue\n' +
    result.code.replace(/^const _Vue = Vue\r?\n?/, '') +
    '\n})();\n';
  fs.writeFileSync(path.join(WEB, 'js', 'render.js'), renderJs);
  console.log(
    `render.js: ${Buffer.byteLength(renderJs)} bytes (template ${Buffer.byteLength(template)} -> compiled ${result.code.length} chars)`,
  );
} else {
  console.log('No template found in index.html or target/ui-build/template.html — skipping template compile');
}

// ---------------------------------------------------------------------------
// 2. Regenerate the Tailwind stylesheet statically
// ---------------------------------------------------------------------------
const tailwindConfig = `/** Generated by target/ui-build/build-web-ui.js. */
module.exports = {
  content: [
    '../../crates/zircon-server/assets/web/index.html',
    '../../crates/zircon-server/assets/web/app.js',
    '../../crates/zircon-server/assets/web/js/*.js',
    // After conversion the template classes live in the compiled render.
    '../../crates/zircon-server/assets/web/js/render.js',
  ],
  theme: {
    extend: {
      colors: {
        emerald: {
          300: '#7be3dc',
          400: '#47d2c9',
          500: '#47d2c9',
          600: '#2f8f88',
          900: '#0f3d3a',
        },
      },
    },
  },
  corePlugins: {
    preflight: true,
  },
};
`;
fs.writeFileSync(path.join(BUILD, 'tailwind.config.js'), tailwindConfig);
fs.writeFileSync(path.join(BUILD, 'tailwind-input.css'), '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n');

execSync(
  `npx tailwindcss -c "${path.join(BUILD, 'tailwind.config.js')}" -i "${path.join(BUILD, 'tailwind-input.css')}" -o "${path.join(BUILD, 'tailwind.out.css')}"`,
  { cwd: BUILD, stdio: 'inherit' },
);

const tailwindCss = fs.readFileSync(path.join(BUILD, 'tailwind.out.css'), 'utf8');
// Preserve the hand-written custom rules (checkboxes, scrollbars, ...) below
// the generated utilities. They live in custom.css (never overwritten) so
// rerunning the build is deterministic.
const customCss = fs.readFileSync(path.join(WEB, 'custom.css'), 'utf8');
fs.writeFileSync(path.join(WEB, 'styles.css'), tailwindCss + '\n' + customCss);
console.log(`styles.css: ${Buffer.byteLength(tailwindCss)} generated + custom merged`);

// ---------------------------------------------------------------------------
// Rewrite index.html. Both operations below use indexes into the untouched
// `html`; the #app template (later in the file) is emptied first, then the CDN
// block (earlier, in <head>) is replaced — neither shift affects the other.
let newHtml = html.slice(0, openEnd) + html.slice(close); // empty #app

// Replace the CDN scripts (Tailwind Play CDN + inline config + Vue full build)
// with the locally vendored Vue runtime build. The Tailwind config now lives
// in the build step, so nothing inline remains. No-op when already converted.
const cdnStart = html.indexOf('    <script src="https://cdn.tailwindcss.com"></script>');
const cdnBlockEndMarker =
  '</script>' +
  CRLF +
  '    <script src="https://unpkg.com/vue@3/dist/vue.global.prod.js"></script>' +
  CRLF;
const cdnEnd = html.indexOf(cdnBlockEndMarker, cdnStart);
if (cdnStart >= 0 && cdnEnd >= 0) {
  newHtml =
    newHtml.slice(0, cdnStart) +
    '    <script src="js/vue.runtime.global.prod.js"></script>' +
    CRLF +
    newHtml.slice(cdnEnd + cdnBlockEndMarker.length);
} else if (!alreadyConverted) {
  throw new Error('could not locate the CDN script block');
}

// Load the pre-compiled render before app.js mounts the app (no-op if the
// script tag was already added by a previous run).
if (!newHtml.includes('<script src="js/render.js"></script>')) {
  newHtml = newHtml.replace(
    '<script src="app.js"></script>',
    '<script src="js/render.js"></script>' + CRLF + '<script src="app.js"></script>',
  );
}

// Keep the file CRLF like the rest of the repository.
fs.writeFileSync(path.join(WEB, 'index.html'), newHtml.replace(/\r?\n/g, CRLF));
console.log('index.html rewritten (local scripts, empty #app, precompiled render)');
