use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-env-changed=CURSEFORGE_API_KEY");
    println!("cargo:rerun-if-changed=../../.env");
    println!("cargo:rerun-if-changed=.env");

    let key = load_curseforge_key();
    let salt: [u8; 8] = [0xA5, 0x5C, 0x39, 0xE7, 0x12, 0x8B, 0xD4, 0x6E];
    let encrypted = obfuscate(key.as_bytes(), &salt);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("curseforge_key_obf.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — non-linear obfuscated CurseForge API key\n");
    code.push_str("const OBFUSCATED_SALT: [u8; 8] = [");
    for (i, b) in salt.iter().enumerate() {
        if i > 0 {
            code.push_str(", ");
        }
        code.push_str(&format!("0x{:02X}", b));
    }
    code.push_str("];\n\n");

    code.push_str("const OBFUSCATED_KEY_BYTES: &[u8] = &[");
    for (i, b) in encrypted.iter().enumerate() {
        if i > 0 {
            code.push_str(", ");
        }
        code.push_str(&format!("0x{:02X}", b));
    }
    code.push_str("];\n\n");

    code.push_str(
        r#"/// Reconstructs the compile-time embedded CurseForge API key on demand in memory.
#[inline(never)]
pub fn deobfuscate_embedded_key() -> String {
    let mut decrypted = Vec::with_capacity(OBFUSCATED_KEY_BYTES.len());
    for (i, &b) in OBFUSCATED_KEY_BYTES.iter().enumerate() {
        let s = OBFUSCATED_SALT[i % OBFUSCATED_SALT.len()];
        let idx_mod = (i as u8).wrapping_mul(0x5Bu8).wrapping_add(0x1F);
        let step3 = b ^ (!(i as u8));
        let step2 = step3.wrapping_sub(idx_mod);
        let step1 = step2.rotate_right(3);
        let orig = step1 ^ s;
        decrypted.push(orig);
    }
    String::from_utf8(decrypted).unwrap_or_default()
}
"#,
    );

    fs::write(&dest_path, code).expect("failed to write obfuscated key file");
}

fn load_curseforge_key() -> String {
    // 1. Check environment variable
    if let Ok(key) = std::env::var("CURSEFORGE_API_KEY") {
        let trimmed = clean_key(&key);
        if !trimmed.is_empty() {
            return trimmed;
        }
    }

    // 2. Check workspace root .env or local .env
    for path in &["../../.env", "../.env", ".env"] {
        if let Ok(contents) = fs::read_to_string(path) {
            for line in contents.lines() {
                let trimmed = line.trim();
                if trimmed.starts_with("CURSEFORGE_API_KEY=") {
                    let raw = trimmed.trim_start_matches("CURSEFORGE_API_KEY=");
                    let cleaned = clean_key(raw);
                    if !cleaned.is_empty() {
                        return cleaned;
                    }
                }
            }
        }
    }

    // 3. Fallback default key
    "$2a$10$HpOnS2ov7lIUxIOlZAMch.8eeVVwIRsi12Vuyj3.sGnyW1wNGGiU6".to_string()
}

fn clean_key(raw: &str) -> String {
    raw.trim().trim_matches('"').trim_matches('\'').to_string()
}

fn obfuscate(input: &[u8], salt: &[u8; 8]) -> Vec<u8> {
    let mut encrypted = Vec::with_capacity(input.len());
    for (i, &b) in input.iter().enumerate() {
        let s = salt[i % salt.len()];
        let idx_mod = (i as u8).wrapping_mul(0x5Bu8).wrapping_add(0x1F);
        let step1 = b ^ s;
        let step2 = step1.rotate_left(3);
        let step3 = step2.wrapping_add(idx_mod);
        let step4 = step3 ^ (!(i as u8));
        encrypted.push(step4);
    }
    encrypted
}
